name: Scheduled Build

on:
  schedule:
    - cron: '0 0 * * 0' # Cada domingo a medianoche

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*' # Utiliza la versión LTS de Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npx astro build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod
